name: Test

on:
  push:
    branches: main
jobs:
  should-run-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking for approval
        uses: actions/checkout@v2
        run: . ./test.sh  